// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipinfo.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpLookupResponse_Error int32

const (
	IpLookupResponse_INVALID_IP     IpLookupResponse_Error = 0
	IpLookupResponse_INTERNAL_ERROR IpLookupResponse_Error = 1
)

var IpLookupResponse_Error_name = map[int32]string{
	0: "INVALID_IP",
	1: "INTERNAL_ERROR",
}

var IpLookupResponse_Error_value = map[string]int32{
	"INVALID_IP":     0,
	"INTERNAL_ERROR": 1,
}

func (x IpLookupResponse_Error) String() string {
	return proto.EnumName(IpLookupResponse_Error_name, int32(x))
}

func (IpLookupResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{1, 0}
}

//
//GET /ip/123.45.67.89
type IpLookupRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpLookupRequest) Reset()         { *m = IpLookupRequest{} }
func (m *IpLookupRequest) String() string { return proto.CompactTextString(m) }
func (*IpLookupRequest) ProtoMessage()    {}
func (*IpLookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{0}
}

func (m *IpLookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpLookupRequest.Unmarshal(m, b)
}
func (m *IpLookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpLookupRequest.Marshal(b, m, deterministic)
}
func (m *IpLookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpLookupRequest.Merge(m, src)
}
func (m *IpLookupRequest) XXX_Size() int {
	return xxx_messageInfo_IpLookupRequest.Size(m)
}
func (m *IpLookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IpLookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IpLookupRequest proto.InternalMessageInfo

func (m *IpLookupRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type IpLookupResponse struct {
	Ip                   string    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostnames            []string  `protobuf:"bytes,2,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Geolocation          *Location `protobuf:"bytes,3,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IpLookupResponse) Reset()         { *m = IpLookupResponse{} }
func (m *IpLookupResponse) String() string { return proto.CompactTextString(m) }
func (*IpLookupResponse) ProtoMessage()    {}
func (*IpLookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{1}
}

func (m *IpLookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpLookupResponse.Unmarshal(m, b)
}
func (m *IpLookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpLookupResponse.Marshal(b, m, deterministic)
}
func (m *IpLookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpLookupResponse.Merge(m, src)
}
func (m *IpLookupResponse) XXX_Size() int {
	return xxx_messageInfo_IpLookupResponse.Size(m)
}
func (m *IpLookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IpLookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IpLookupResponse proto.InternalMessageInfo

func (m *IpLookupResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *IpLookupResponse) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *IpLookupResponse) GetGeolocation() *Location {
	if m != nil {
		return m.Geolocation
	}
	return nil
}

type Location struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Lat                  float64  `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,5,opt,name=long,proto3" json:"long,omitempty"`
	Timezone             string   `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Location) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.IpLookupResponse_Error", IpLookupResponse_Error_name, IpLookupResponse_Error_value)
	proto.RegisterType((*IpLookupRequest)(nil), "api.IpLookupRequest")
	proto.RegisterType((*IpLookupResponse)(nil), "api.IpLookupResponse")
	proto.RegisterType((*Location)(nil), "api.Location")
}

func init() { proto.RegisterFile("ipinfo.proto", fileDescriptor_3f776f3a264ad8cc) }

var fileDescriptor_3f776f3a264ad8cc = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x4d, 0xbb, 0xcd, 0xf5, 0xdb, 0x9c, 0xe5, 0x3b, 0x05, 0xf1, 0xd0, 0xf5, 0x54, 0x10,
	0x26, 0xe8, 0x2f, 0x18, 0xba, 0x43, 0xa1, 0x54, 0x09, 0xe2, 0xb5, 0xd4, 0x2e, 0xce, 0x60, 0x97,
	0x2f, 0xb6, 0xe9, 0x61, 0xfe, 0x17, 0xfd, 0xad, 0xb2, 0xd0, 0x39, 0xf1, 0xf6, 0xbe, 0x4f, 0x9e,
	0x84, 0x97, 0xc0, 0x54, 0x19, 0xa5, 0x5f, 0x69, 0x61, 0x1a, 0xb2, 0x84, 0x7e, 0x69, 0x54, 0x3c,
	0x87, 0xf3, 0xd4, 0x64, 0x44, 0xef, 0x9d, 0x11, 0xf2, 0xa3, 0x93, 0xad, 0xc5, 0x19, 0x78, 0xca,
	0x70, 0x16, 0xb1, 0x24, 0x10, 0x9e, 0x32, 0xf1, 0x37, 0x83, 0xf0, 0xe8, 0xb4, 0x86, 0x74, 0x2b,
	0xff, 0x4b, 0x78, 0x09, 0xc1, 0x1b, 0xb5, 0x56, 0x97, 0x5b, 0xd9, 0x72, 0x2f, 0xf2, 0x93, 0x40,
	0x1c, 0x01, 0x5e, 0xc3, 0x64, 0x23, 0xa9, 0xa6, 0xaa, 0xb4, 0x8a, 0x34, 0xf7, 0x23, 0x96, 0x4c,
	0x6e, 0xce, 0x16, 0xa5, 0x51, 0x8b, 0xac, 0x87, 0xe2, 0xaf, 0x11, 0x5f, 0xc1, 0x70, 0xd5, 0x34,
	0xd4, 0xe0, 0x0c, 0x20, 0xcd, 0x9f, 0x97, 0x59, 0x7a, 0x5f, 0xa4, 0x8f, 0xe1, 0x09, 0x22, 0xcc,
	0xd2, 0xfc, 0x69, 0x25, 0xf2, 0x65, 0x56, 0xac, 0x84, 0x78, 0x10, 0x21, 0x8b, 0xbf, 0x18, 0x8c,
	0x0f, 0xcf, 0xe0, 0x1c, 0xa6, 0x15, 0x75, 0xda, 0x36, 0xbb, 0xa2, 0xa2, 0xb5, 0xec, 0x27, 0x4e,
	0x7a, 0x76, 0x47, 0x6b, 0x89, 0x1c, 0x4e, 0xfb, 0xca, 0x3d, 0x77, 0x7a, 0xa8, 0x88, 0x30, 0xa8,
	0x94, 0xdd, 0xb9, 0x81, 0x81, 0x70, 0x19, 0x43, 0xf0, 0xeb, 0xd2, 0xf2, 0x41, 0xc4, 0x12, 0x26,
	0xf6, 0x71, 0x6f, 0xd5, 0xa4, 0x37, 0x7c, 0xe8, 0x90, 0xcb, 0x78, 0x01, 0x63, 0xab, 0xb6, 0xf2,
	0x93, 0xb4, 0xe4, 0x23, 0x77, 0xfb, 0xb7, 0xbf, 0x8c, 0xdc, 0x7f, 0xdf, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0x94, 0x15, 0xf2, 0x7f, 0x01, 0x00, 0x00,
}
