// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipinfo.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//These are the error codes which can be returned by this endpoint. In case of an error, an ErrorResponse will be returned
type WhatsMyIpResponse_Error int32

const (
	WhatsMyIpResponse_INVALID_IP     WhatsMyIpResponse_Error = 0
	WhatsMyIpResponse_INTERNAL_ERROR WhatsMyIpResponse_Error = 1
)

var WhatsMyIpResponse_Error_name = map[int32]string{
	0: "INVALID_IP",
	1: "INTERNAL_ERROR",
}

var WhatsMyIpResponse_Error_value = map[string]int32{
	"INVALID_IP":     0,
	"INTERNAL_ERROR": 1,
}

func (x WhatsMyIpResponse_Error) String() string {
	return proto.EnumName(WhatsMyIpResponse_Error_name, int32(x))
}

func (WhatsMyIpResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{1, 0}
}

//These are the error codes which can be returned by this endpoint. In case of an error, an ErrorResponse will be returned
type LookupIpResponse_Error int32

const (
	LookupIpResponse_INVALID_IP     LookupIpResponse_Error = 0
	LookupIpResponse_INTERNAL_ERROR LookupIpResponse_Error = 1
)

var LookupIpResponse_Error_name = map[int32]string{
	0: "INVALID_IP",
	1: "INTERNAL_ERROR",
}

var LookupIpResponse_Error_value = map[string]int32{
	"INVALID_IP":     0,
	"INTERNAL_ERROR": 1,
}

func (x LookupIpResponse_Error) String() string {
	return proto.EnumName(LookupIpResponse_Error_name, int32(x))
}

func (LookupIpResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{3, 0}
}

//These are the error codes which can be returned by this endpoint. In case of an error, an ErrorResponse will be returned
type LookupHostResponse_Error int32

const (
	LookupHostResponse_INVALID_HOSTNAME LookupHostResponse_Error = 0
	LookupHostResponse_INTERNAL_ERROR   LookupHostResponse_Error = 1
	LookupHostResponse_NOT_FOUND        LookupHostResponse_Error = 2
)

var LookupHostResponse_Error_name = map[int32]string{
	0: "INVALID_HOSTNAME",
	1: "INTERNAL_ERROR",
	2: "NOT_FOUND",
}

var LookupHostResponse_Error_value = map[string]int32{
	"INVALID_HOSTNAME": 0,
	"INTERNAL_ERROR":   1,
	"NOT_FOUND":        2,
}

func (x LookupHostResponse_Error) String() string {
	return proto.EnumName(LookupHostResponse_Error_name, int32(x))
}

func (LookupHostResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{5, 0}
}

//
//GET /ip
type WhatsMyIpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhatsMyIpRequest) Reset()         { *m = WhatsMyIpRequest{} }
func (m *WhatsMyIpRequest) String() string { return proto.CompactTextString(m) }
func (*WhatsMyIpRequest) ProtoMessage()    {}
func (*WhatsMyIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{0}
}

func (m *WhatsMyIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatsMyIpRequest.Unmarshal(m, b)
}
func (m *WhatsMyIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatsMyIpRequest.Marshal(b, m, deterministic)
}
func (m *WhatsMyIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatsMyIpRequest.Merge(m, src)
}
func (m *WhatsMyIpRequest) XXX_Size() int {
	return xxx_messageInfo_WhatsMyIpRequest.Size(m)
}
func (m *WhatsMyIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatsMyIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhatsMyIpRequest proto.InternalMessageInfo

type WhatsMyIpResponse struct {
	Ip                   string    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	ForwardedFor         string    `protobuf:"bytes,2,opt,name=forwardedFor,proto3" json:"forwardedFor,omitempty"`
	Hostnames            []string  `protobuf:"bytes,3,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Geolocation          *Location `protobuf:"bytes,4,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WhatsMyIpResponse) Reset()         { *m = WhatsMyIpResponse{} }
func (m *WhatsMyIpResponse) String() string { return proto.CompactTextString(m) }
func (*WhatsMyIpResponse) ProtoMessage()    {}
func (*WhatsMyIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{1}
}

func (m *WhatsMyIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatsMyIpResponse.Unmarshal(m, b)
}
func (m *WhatsMyIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatsMyIpResponse.Marshal(b, m, deterministic)
}
func (m *WhatsMyIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatsMyIpResponse.Merge(m, src)
}
func (m *WhatsMyIpResponse) XXX_Size() int {
	return xxx_messageInfo_WhatsMyIpResponse.Size(m)
}
func (m *WhatsMyIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatsMyIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhatsMyIpResponse proto.InternalMessageInfo

func (m *WhatsMyIpResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *WhatsMyIpResponse) GetForwardedFor() string {
	if m != nil {
		return m.ForwardedFor
	}
	return ""
}

func (m *WhatsMyIpResponse) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *WhatsMyIpResponse) GetGeolocation() *Location {
	if m != nil {
		return m.Geolocation
	}
	return nil
}

//
//GET /ip?ipAddress=123.45.67.89
type LookupIpRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupIpRequest) Reset()         { *m = LookupIpRequest{} }
func (m *LookupIpRequest) String() string { return proto.CompactTextString(m) }
func (*LookupIpRequest) ProtoMessage()    {}
func (*LookupIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{2}
}

func (m *LookupIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupIpRequest.Unmarshal(m, b)
}
func (m *LookupIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupIpRequest.Marshal(b, m, deterministic)
}
func (m *LookupIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupIpRequest.Merge(m, src)
}
func (m *LookupIpRequest) XXX_Size() int {
	return xxx_messageInfo_LookupIpRequest.Size(m)
}
func (m *LookupIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupIpRequest proto.InternalMessageInfo

func (m *LookupIpRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type LookupIpResponse struct {
	Ip                   string    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostnames            []string  `protobuf:"bytes,2,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Geolocation          *Location `protobuf:"bytes,3,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LookupIpResponse) Reset()         { *m = LookupIpResponse{} }
func (m *LookupIpResponse) String() string { return proto.CompactTextString(m) }
func (*LookupIpResponse) ProtoMessage()    {}
func (*LookupIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{3}
}

func (m *LookupIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupIpResponse.Unmarshal(m, b)
}
func (m *LookupIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupIpResponse.Marshal(b, m, deterministic)
}
func (m *LookupIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupIpResponse.Merge(m, src)
}
func (m *LookupIpResponse) XXX_Size() int {
	return xxx_messageInfo_LookupIpResponse.Size(m)
}
func (m *LookupIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupIpResponse proto.InternalMessageInfo

func (m *LookupIpResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LookupIpResponse) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *LookupIpResponse) GetGeolocation() *Location {
	if m != nil {
		return m.Geolocation
	}
	return nil
}

//
//GET /host?hostname=ipinfo.xyz
type LookupHostRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupHostRequest) Reset()         { *m = LookupHostRequest{} }
func (m *LookupHostRequest) String() string { return proto.CompactTextString(m) }
func (*LookupHostRequest) ProtoMessage()    {}
func (*LookupHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{4}
}

func (m *LookupHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupHostRequest.Unmarshal(m, b)
}
func (m *LookupHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupHostRequest.Marshal(b, m, deterministic)
}
func (m *LookupHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupHostRequest.Merge(m, src)
}
func (m *LookupHostRequest) XXX_Size() int {
	return xxx_messageInfo_LookupHostRequest.Size(m)
}
func (m *LookupHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupHostRequest proto.InternalMessageInfo

func (m *LookupHostRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type LookupHostResponse struct {
	Ips                  []string  `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	Hostnames            []string  `protobuf:"bytes,2,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Geolocation          *Location `protobuf:"bytes,3,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LookupHostResponse) Reset()         { *m = LookupHostResponse{} }
func (m *LookupHostResponse) String() string { return proto.CompactTextString(m) }
func (*LookupHostResponse) ProtoMessage()    {}
func (*LookupHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{5}
}

func (m *LookupHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupHostResponse.Unmarshal(m, b)
}
func (m *LookupHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupHostResponse.Marshal(b, m, deterministic)
}
func (m *LookupHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupHostResponse.Merge(m, src)
}
func (m *LookupHostResponse) XXX_Size() int {
	return xxx_messageInfo_LookupHostResponse.Size(m)
}
func (m *LookupHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupHostResponse proto.InternalMessageInfo

func (m *LookupHostResponse) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *LookupHostResponse) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *LookupHostResponse) GetGeolocation() *Location {
	if m != nil {
		return m.Geolocation
	}
	return nil
}

type Location struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Lat                  float64  `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,5,opt,name=long,proto3" json:"long,omitempty"`
	Timezone             string   `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f776f3a264ad8cc, []int{6}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Location) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.WhatsMyIpResponse_Error", WhatsMyIpResponse_Error_name, WhatsMyIpResponse_Error_value)
	proto.RegisterEnum("api.LookupIpResponse_Error", LookupIpResponse_Error_name, LookupIpResponse_Error_value)
	proto.RegisterEnum("api.LookupHostResponse_Error", LookupHostResponse_Error_name, LookupHostResponse_Error_value)
	proto.RegisterType((*WhatsMyIpRequest)(nil), "api.WhatsMyIpRequest")
	proto.RegisterType((*WhatsMyIpResponse)(nil), "api.WhatsMyIpResponse")
	proto.RegisterType((*LookupIpRequest)(nil), "api.LookupIpRequest")
	proto.RegisterType((*LookupIpResponse)(nil), "api.LookupIpResponse")
	proto.RegisterType((*LookupHostRequest)(nil), "api.LookupHostRequest")
	proto.RegisterType((*LookupHostResponse)(nil), "api.LookupHostResponse")
	proto.RegisterType((*Location)(nil), "api.Location")
}

func init() { proto.RegisterFile("ipinfo.proto", fileDescriptor_3f776f3a264ad8cc) }

var fileDescriptor_3f776f3a264ad8cc = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x71, 0xb2, 0x8d, 0xe5, 0xb4, 0x2b, 0xd9, 0x11, 0x17, 0x16, 0xe2, 0xa2, 0x0b, 0x37,
	0x95, 0x90, 0x8a, 0x04, 0x2f, 0x40, 0xc5, 0x3a, 0x2d, 0x52, 0x97, 0x20, 0x53, 0xe0, 0x32, 0x0a,
	0x89, 0xb7, 0x59, 0x74, 0x39, 0xc6, 0x76, 0x85, 0xca, 0xbb, 0xc0, 0x6b, 0xf0, 0x00, 0xbc, 0x18,
	0x8a, 0x49, 0xb6, 0x0e, 0x31, 0x71, 0xb3, 0xbb, 0xff, 0xfc, 0xf9, 0x63, 0xfd, 0x9f, 0x75, 0x0c,
	0x43, 0xa5, 0x55, 0x73, 0x4e, 0x53, 0x6d, 0xc8, 0x11, 0x86, 0xa5, 0x56, 0x09, 0x42, 0xfc, 0xf1,
	0xb2, 0x74, 0xf6, 0x6c, 0x93, 0x6a, 0x21, 0xbf, 0xac, 0xa5, 0x75, 0xc9, 0x2f, 0x06, 0x87, 0x5b,
	0xa6, 0xd5, 0xd4, 0x58, 0x89, 0x23, 0x08, 0x94, 0xe6, 0x6c, 0xcc, 0x26, 0x91, 0x08, 0x94, 0xc6,
	0x04, 0x86, 0xe7, 0x64, 0xbe, 0x96, 0xa6, 0x96, 0xf5, 0x09, 0x19, 0x1e, 0xf8, 0x2f, 0xb7, 0x3c,
	0x7c, 0x0a, 0xd1, 0x25, 0x59, 0xd7, 0x94, 0x57, 0xd2, 0xf2, 0x70, 0x1c, 0x4e, 0x22, 0x71, 0x63,
	0xe0, 0x0b, 0x18, 0x5c, 0x48, 0x5a, 0x51, 0x55, 0x3a, 0x45, 0x0d, 0xdf, 0x19, 0xb3, 0xc9, 0xe0,
	0xe5, 0xc1, 0xb4, 0xd4, 0x6a, 0xba, 0xe8, 0x4c, 0xb1, 0x9d, 0x48, 0x9e, 0xc3, 0xee, 0xdc, 0x18,
	0x32, 0x38, 0x02, 0x48, 0xb3, 0x0f, 0xb3, 0x45, 0x7a, 0x5c, 0xa4, 0x6f, 0xe3, 0x07, 0x88, 0x30,
	0x4a, 0xb3, 0xe5, 0x5c, 0x64, 0xb3, 0x45, 0x31, 0x17, 0x22, 0x17, 0x31, 0x4b, 0x8e, 0xe0, 0xd1,
	0x82, 0xe8, 0xf3, 0x5a, 0x5f, 0x83, 0xfd, 0x8d, 0x90, 0xfc, 0x60, 0x10, 0xdf, 0x64, 0xee, 0xe0,
	0xbc, 0xc5, 0x10, 0xfc, 0x87, 0x21, 0xbc, 0x5f, 0x86, 0x67, 0x70, 0xf8, 0xa7, 0xdf, 0x29, 0x59,
	0x77, 0x17, 0xc5, 0x4f, 0x06, 0xb8, 0x9d, 0xea, 0x38, 0x62, 0x08, 0x95, 0xb6, 0x9c, 0xf9, 0xc6,
	0xad, 0xbc, 0x6f, 0x92, 0xd7, 0x3d, 0xc9, 0x63, 0x88, 0x7b, 0x92, 0xd3, 0xfc, 0xdd, 0x32, 0x9b,
	0x9d, 0xcd, 0xff, 0xcd, 0x83, 0x07, 0x10, 0x65, 0xf9, 0xb2, 0x38, 0xc9, 0xdf, 0x67, 0xc7, 0x71,
	0x90, 0x7c, 0x67, 0xb0, 0xdf, 0x9f, 0x8d, 0x47, 0x30, 0xac, 0x68, 0xdd, 0x38, 0xb3, 0x29, 0x2a,
	0xaa, 0x65, 0x07, 0x38, 0xe8, 0xbc, 0x37, 0x54, 0x4b, 0xe4, 0xf0, 0xb0, 0x1b, 0xbb, 0x6d, 0xeb,
	0x47, 0x44, 0xd8, 0xa9, 0x94, 0xdb, 0xf8, 0xd6, 0x91, 0xf0, 0xba, 0xbd, 0x80, 0x55, 0xe9, 0xfc,
	0x5a, 0x31, 0xd1, 0xca, 0x36, 0xb5, 0xa2, 0xe6, 0x82, 0xef, 0x7a, 0xcb, 0x6b, 0x7c, 0x02, 0xfb,
	0x4e, 0x5d, 0xc9, 0x6f, 0xd4, 0x48, 0xbe, 0xe7, 0xff, 0xbe, 0x9e, 0x3f, 0xed, 0xf9, 0x87, 0xf2,
	0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x5c, 0x49, 0xeb, 0x38, 0x03, 0x00, 0x00,
}
